# Terraform Provider testing workflow.
name: Tests

# This GitHub action runs your tests for each pull request and push.
# Optionally, you can turn it on using a schedule for regular testing.
on:
    pull_request:
        paths-ignore:
            - 'CHANGELOG.md'
            - 'README.md'
    push:
        branches:
            - main
        paths-ignore:
            - 'CHANGELOG.md'
            - 'README.md'

env:
    LC_APPLICATION_ID: terraform-provider-sonatyperepo
    NEXUS_SECURITY_RANDOMPASSWORD: "false"
    INSTALL4J_ADD_VM_PARAMS: "-Dnexus.licenseFile=${{ github.workspace }}/license.lic"

# Testing only needs permissions to read the repository contents.
permissions:
    contents: read

jobs:
    # Ensure project builds before running testing matrix
    build:
        name: Build
        runs-on: ubuntu-latest
        timeout-minutes: 5
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                  go-version-file: 'go.mod'
                  cache: true
            - run: go mod download
            - run: go build -v .
            - name: Run linters
              uses: golangci/golangci-lint-action@v8
              with:
                  version: latest
            
    sonatype:
        name: Sonatype Scan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              
            - uses: actions/setup-go@v5
              with:
                go-version-file: 'go.mod'
                cache: true
              
            - name: Generate go.list
              run:
                    go list -f '{{define "M"}}{{.Path}} {{.Version}}{{end}}{{with .Module}}{{if not .Main}}{{if .Replace}}{{template "M" .Replace}}{{else}}{{template "M" .}}{{end}}{{end}}{{end}}' -compiled -deps| sort -u > go.list
              
            - name: Sonatype Lifecycle Evaluation
              id: evaluate
              uses: sonatype/actions/evaluate@v1
              with:
                    iq-server-url: ${{ vars.SONATYPE_PLATFORM_URL }}
                    username: ${{ secrets.SONATYPE_LIFECYCLE_USERNAME }}
                    password: ${{ secrets.SONATYPE_LIFECYCLE_PASSWORD }}
                    application-id: ${{ env.LC_APPLICATION_ID }}
                    scan-targets: 'go.list'
                    stage: build

    generate:
        name: Ensure Docs are Generated
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              
            - uses: actions/setup-go@v5
              with:
                  go-version-file: 'go.mod'
                  cache: true

            - uses: hashicorp/setup-terraform@v3
              with:
                terraform_version: 1.4.5
                terraform_wrapper: false
            
            - name: Generate Docs
              run: go generate ./...
              working-directory: tools

            - name: Check fo Documentation Diffs
              run: |
                  git diff --compact-summary --exit-code || \
                    (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' in `tools` directory command and commit."; exit 1)

    # Run acceptance tests in a matrix with Terraform CLI versions
    test-parallel:
        name: Acc. Tests (NXRM ${{ matrix.nxrm }} + TF ${{ matrix.terraform }})
        needs: 
            - build
            - sonatype
            - generate
        runs-on: ubuntu-latest
        timeout-minutes: 15
        strategy:
            fail-fast: false
            matrix:
                nxrm:
                    # - '3.77.2-02' # N-5
                    - '3.78.2-04' # FIRST WITH BUNDLED JRE
                    - '3.79.1-04' 
                    - '3.80.0-06' 
                    - '3.81.1-01' # LATEST
                # list whatever Terraform versions here you would like to support
                terraform:
                    - '1.0.*' # Minimum
                    # - '1.1.*'
                    # - '1.2.*'
                    # - '1.3.*'
                    # - '1.4.*'
                    # - '1.5.*'
                    # - '1.6.*'
                    # - '1.7.*'
                    # - '1.8.*'
                    # - '1.9.*'
                    # - '1.10.*'
                    # - '1.11.*' 
                    - '1.12.*' # Latest
                    # - '1.13.*'
                    # - '1.14.*'
        steps:
            - name: Download & Unpack Sonatype Nexus Repository Manager
              run: |
                  echo "${{ secrets.NXRM_LICENSE }}" | base64 -d > ${{ github.workspace }}/license.lic
                  wget https://download.sonatype.com/nexus/3/nexus-${{ matrix.nxrm }}-linux-x86_64.tar.gz 
                  tar xvz --keep-directory-symlink -f nexus-${{ matrix.nxrm }}-linux-x86_64.tar.gz 
                  sed -i '1s/^.*$/#!\/bin\/bash/' ${{ github.workspace }}/nexus-${{ matrix.nxrm }}/bin/nexus
                  head -5 ${{ github.workspace }}/nexus-${{ matrix.nxrm }}/bin/nexus

            - name: Start Sonatype Nexus Repository Manager
              run: ./nexus start
              working-directory: "${{ github.workspace }}/nexus-${{ matrix.nxrm }}/bin"

            - name: Wait for Sonatype Nexus Repository Manager to be ready
              run: |
                  set +e
                  sleep 20
                  while true; do
                    STATUS=$(curl -s -o /dev/null -w "%{http_code}" "http://localhost:8081/service/rest/v1/status")
                    CURL_EXIT=$?

                    echo "CURL Exit Code: $CURL_EXIT"

                    if [ "$CURL_EXIT" -eq 0 ]; then
                      if [ "$STATUS" -eq 200 ]; then
                          echo "✅ Received 200 OK from http://localhost:8081/service/rest/v1/status"
                          break
                      else
                          echo "⏳ Waiting for 200 OK... Current status: $STATUS for http://localhost:8081/service/rest/v1/status"
                          sleep 5
                      fi
                    else
                      echo "⚠️ curl returned unexpected exit code $CURL_EXIT. Retrying..."
                      sleep 5
                    fi
                  done

            - name: Checkout Source
              uses: actions/checkout@v4
              
            - uses: actions/setup-go@v5
              with:
                  go-version-file: 'go.mod'
                  cache: true
            - uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ matrix.terraform }}
                  terraform_wrapper: false
            - run: go mod download
            - env:
                  NXRM_SERVER_URL: "http://localhost:8081"
                  NXRM_SERVER_USERNAME: "admin"
                  NXRM_SERVER_PASSWORD: "admin123"
                  TF_ACC: '1'
                  TF_ACC_SINGLE_HIT: '1'
              run: go test -v -cover ./...
              timeout-minutes: 10